### ISSUE TITLE
Loader Spinner Doubling in Full Screen Mode

### ISSUE THREAD

**Issue by Jankstar11** [ktg5/PlayerTube#12]
In the latest workflow run with v1.5.2.1 as of posting I am experiencing two loading spinners when in full screen mode. The reason I did not download v1.5.2 of the Chrome Web Store extension to report this issue is because it did not load the old video player design at all.

Workflow v1.5.2.1 issue screenshot:
![PlayerTube v1 5 2 1 Loading Spinner Bug](https://github.com/ktg5/PlayerTube/assets/113773450/68d634bc-74f9-4a02-8773-572b53c2fabf)
Chrome Web Store v1.5.2 issue screenshot: 
![PlayerTube v1 5 2 Not Loading](https://github.com/ktg5/PlayerTube/assets/113773450/f2500254-7412-4d7b-b4d5-f43a640c8566)

Browser: Vivaldi
Extension Settings: Only "Fully extend the Progress Bar's height at all times" was enabled for workflow v1.5.2.1 and no settings were changed for v1.5.2 of the Chrome Web Store extension.

**Comment by ktg5** [comment]
Version 1.5.2.2 should be public as of now, which includes the fix for this.
