### ISSUE TITLE
[ Bug ] Player Icons broken

### ISSUE THREAD

**Issue by ZyrusplaysAnimations** [ktg5/PlayerTube#14]
**Describe the bug**
Extension working normally last 3 weeks until it broke today. The player works but the icons were all broken. I am using the 2012 player, but if I use the 2015 player, it doesn't have icons and the buttons are broken. I tried to disable then reenable, pressing the big "nuke" button, uninstall then reinstall the extension and none of them fixed this problem. The only has icons is the 2010 player but the settings icon is missing.

**Screenshots**
2012 player
![image](https://github.com/ktg5/PlayerTube/assets/70579850/f8214358-c494-4ff6-a0d6-9de766de9260)

2015 player
![image](https://github.com/ktg5/PlayerTube/assets/70579850/04b2fcdb-82be-4c4b-9968-73427540ab88)

2010 player
![image](https://github.com/ktg5/PlayerTube/assets/70579850/a2a89df7-0064-43af-a7d8-6309da4ad852)

**To Reproduce**
1. Load a video.
2. Let the player loads then bug.

**Browser / Extension information**
- Extension version: PlayerTube 1.5.2.2
- Browser information: Chrome 120.0.6099.200 (Official Build) (64-bit)

**Comment by ktg5** [comment]
I feel like such a idiot because I know why this is happening. I changed the names for the icons yesterday night without any thought, will get this fixed ASAP.

**Comment by ktg5** [comment]
Uploaded v1.6 to Chrome & Firefox web-stores which should fix the issue. In the future, I should figure out how to use the extension's storage instead of depending on GitHub's website
