### ISSUE TITLE
2006 Player | Progress Bar & Other Issues

### ISSUE THREAD

**Issue by 777Sev777** [ktg5/PlayerTube#16]
### A clear and concise description of what the bug is.

Hi, got a small bug report. I'm not sure if the 2006 player theme is fully complete or still being worked on so i thought i'd submit this in case you were not already aware of it. the rest of the layouts looks and work great as always but the 2006 layout is pretty bugged out which can be seen in the screen shot.

### If applicable, add screenshots to help explain your problem.

![Capture](https://github.com/ktg5/PlayerTube/assets/134644571/64c5780c-de78-485e-9659-a5493171cfc8)

### What should actually happen instead of the issue.

I assume this is what the player should actually look like:

![43242](https://github.com/ktg5/PlayerTube/assets/134644571/5f727b5f-85aa-491f-9d77-92b5493a7f24)

### Steps to reproduce the behavior.

im not 100% sure if this is a issue on my end or if this is reproducible or a recurring issue for other users 

### PlayerTube settings. (Can be found under "Import, Copy, or Reset Settings")

{
 "autoplayButton": false,
 "controlsBack": null,
 "customTheme": true,
 "darkMode": false,
 "embedOtherVideos": true,
 "endScreenToggle": true,
 "fakeBarToggle": true,
 "fullyExtendBar": false,
 "heatMapToggle": true,
 "progressBarBgColor": null,
 "progressBarColor": "#ff0000",
 "scrubberHeight": null,
 "scrubberIcon": null,
 "scrubberIconHover": null,
 "scrubberLeft": null,
 "scrubberPosition": null,
 "scrubberSize": null,
 "scrubberTop": null,
 "scrubberWidth": null,
 "settingsBgColor": null,
 "showReleaseNotes": true,
 "toggleFadeOut": false,
 "toggleInfoCards": true,
 "togglePaidContent": false,
 "toggleRoundedCorners": false,
 "toggleWatermark": true,
 "volumeSliderBack": null,
 "year": "2006"
}
            

### Browser / Extension information.

The only extensions for youtube i use are CustomTube and some custom CSS scripts i made that dont effect the actual youtube watch page elements like the player etc used with this extension.

**Comment by ktg5** [comment]
Since you're using CustomTube, make sure you have your CustomTube  settings set to what is in this screenshot: https://github.com/ktg5/PlayerTube/blob/main/img/customtube-settings.png
But I haven't seen an issue like this yet. Unsure what else it could be if it's not CustomTube messing with it.

**Comment by ktg5** [comment]
Any update on this?

**Comment by nextepwastaken** [comment]
Little late to this. I tested it out on Firefox and Microsoft Edge, with and without CustomTube. I fiddled with the settings, tried disabling CustomTube, reinstalled both extensions, and even tried different screen resolutions, but it seems to just be a general issue with the style, which is weird considering the other styles work perfectly. (the gap is a completely separate issue from customtube)
<img width="518" alt="firefox1" src="https://github.com/ktg5/PlayerTube/assets/151408852/94e84793-5aed-47bd-9b5a-571691dc23d2">
<img width="516" alt="firefox2" src="https://github.com/ktg5/PlayerTube/assets/151408852/0f147ceb-3fe0-494a-a7bf-5ddf63494302">

**Comment by 777Sev777** [comment]
yeah I've come to the same conclusion after messing around with and testing with and without custom tube etc. its def not an issue with customtube compatibility. not sure specifically what would be causing it specifically, the rest of the styles work perfect so im not sure if its a problem in the CSS but im glad to learn im not the only one experiencing this issue.

**Comment by ktg5** [comment]
Seems to be multiple variations of issues with this theme, unsure if I'll be able to get each one fixed. But I'm working on fixing all of this right now.

**Comment by ktg5** [comment]
Sending out a new version of PlayerTube right now that should fix these issues. The reason for some stuff not moving is that the moving elements part of the 2006 theme script was looking for an element that isn't in vanilla YouTube (sorry about that lol).

**Comment by SussyBox** [comment]
It works, but now its flickering

**Comment by ktg5** [comment]
I think I know what you mean -- does the Progress Bar change sizes very quickly?

**Comment by SussyBox** [comment]
https://github.com/ktg5/PlayerTube/assets/102433489/8e19894e-ea58-42f1-82d9-d600f41c730
yea. heres some footage of it.

**Comment by ktg5** [comment]
> The issue seems to now be with CustomTube and Firefox. When CustomTube was on with both browsers, the resizing effect continues, same as the previous screenshots. On Microsoft Edge, the resizing effect does not happen at all, with or without theater mode enabled. However, on Firefox, it continues to happen outside of theater mode, albeit more minuscule.

Can't replicate

> It keeps showing up.

Will fix

**Comment by ktg5** [comment]
> The issue seems to now be with CustomTube and Firefox. When CustomTube was on with both browsers, the resizing effect continues, same as the previous screenshots. On Microsoft Edge, the resizing effect does not happen at all, with or without theater mode enabled. However, on Firefox, it continues to happen outside of theater mode, albeit more minuscule. <img alt="firefox3" width="680" src="https://private-user-images.githubusercontent.com/151408852/297237260-e9b3368a-6e25-4b05-96af-1b983d55383c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NjA4MjQsIm5iZiI6MTcwNTQ2MDUyNCwicGF0aCI6Ii8xNTE0MDg4NTIvMjk3MjM3MjYwLWU5YjMzNjhhLTZlMjUtNGIwNS05NmFmLTFiOTgzZDU1MzgzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QwMzAyMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmJkYzdkMjM1ZTdhZWM5ZjRkOGQ4MTdmZDAxM2RjYmYzNTliNDYyZjEzYzhkZWE4MmFmMGQzZTg1OTNkMGNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GpDkhR0dAjO0kTZ3KWDdjuqhvZL7TgIEF3fKmjHVLEg"> <img alt="firefox4" width="683" src="https://private-user-images.githubusercontent.com/151408852/297237266-84907c00-8fca-47ac-8822-cd6c5f9056b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NjA4MjQsIm5iZiI6MTcwNTQ2MDUyNCwicGF0aCI6Ii8xNTE0MDg4NTIvMjk3MjM3MjY2LTg0OTA3YzAwLThmY2EtNDdhYy04ODIyLWNkNmM1ZjkwNTZiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QwMzAyMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNmY1NTAyN2E2YTMzMmI0NzQ1ZGQ3NDdlOGNiZjU1ODU3YzBlODJmODhlMDBjMDcyNTYxYjU2Y2U4OGNmZjVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lun9QFR9B_dZA65EblXEmk8S9zzw-ORtZrhsxi6Pt0M">

Can't seem to replicate any of the issues described here

> It keeps showing up.
> 
>  2024-01-16.18-10-58.mp4

Will be fixing this.

**Comment by ktg5** [comment]
New fix on the Actions page for the thing that "SussyBox" was talking about.
If there's little more issues, send them in with good detail.

**Comment by ktg5** [comment]
I don't know what else to say. On my side, everything works fine. If you wanna look through the code, be my guest, [the resize code for PlayerTube can be found here](https://github.com/ktg5/PlayerTube/blob/main/src/resize.js). I put as many comments around my code as I can, so it should be easy to understand.

But generally, the math for the Progress Bar uses (the video's width) - (whatever offset, which is currently 56) - (the size of the right controls)
The reason for most of the Progress Bar's past glitching is due to the fact that YouTube's website has **another hidden script** (love these!) which turns some buttons to `display: none` if the right controls get to a current size. After the recent update, it works fine for me, but I'm unsure what else could be causing problems when I'm not having any issues on my side.

**Comment by 777Sev777** [comment]
> I don't know what else to say. On my side, everything works fine. If you wanna look through the code, be my guest, [the resize code for PlayerTube can be found here](https://github.com/ktg5/PlayerTube/blob/main/src/resize.js). I put as many comments around my code as I can, so it should be easy to understand.
> 
> But generally, the math for the Progress Bar uses (the video's width) - (whatever offset, which is currently 56) - (the size of the right controls) The reason for most of the Progress Bar's past glitching is due to the fact that YouTube's website has **another hidden script** (love these!) which turns some buttons to `display: none` if the right controls get to a current size. After the recent update, it works fine for me, but I'm unsure what else could be causing problems when I'm not having any issues on my side.

yeah i understand, and true youtube is really weird sometimes with custom scripts and extensions. ill poke around a bit. regardless this is one of my fav extensions for yt. and you have done a great job recreating stuff, keep up the great work and thank you for making it public. cant wait for more updates.

**Comment by ktg5** [comment]
Putting this as resolved for now, feel free to open another issue if anything new pops up
