### ISSUE TITLE
Firefox: Some PlayerTube images not showing.

### ISSUE THREAD

**Issue by ktg5** [ktg5/PlayerTube#17]
This is an issue I should’ve known about, and I apologize to our Firefox users.
This is caused by the recent update of using the extension’s storage for the images and assets. This will be fixed in a v1.6.1.1 only for Firefox and a "patched" version on our releases page.

**Comment by Not-A-Coder2023** [comment]
Hold on I was about to say the same thing💀

**Comment by ktg5** [comment]
Fixed now -- going to be uploaded to web-stores in a few.
