### ISSUE TITLE
"HD" Lettering Not Showing on Settings Button

### ISSUE THREAD

**Issue by OleExploder** [ktg5/PlayerTube#18]
### A clear and concise description of what the bug is.

In this bug, the HD lettering is not showing on the Settings button but only when not in full screen mode and that includes theatre mode too.

### If applicable, add screenshots to help explain your problem.

![Screenshot 2024-01-13 195501](https://github.com/ktg5/PlayerTube/assets/113773450/68d63ec2-8ce0-4a99-830b-e0de8e6d6ab0)

### What should actually happen instead of the issue.

The HD lettering is supposed to show whether or not a YouTube video is in full screen mode.

### Steps to reproduce the behavior.

Do not go into full screen mode and the bug will show up.

### PlayerTube settings. (Can be found under "Import, Copy, or Reset Settings")

"Toggle Alternate Theme mode for your current theme" and "Fully extend the Progress Bar's height at all times" is enabled but all other settings are unchanged from installing the extension.

### Browser / Extension information.

Extension: PlayerTube v1.6.1
Browser: Vivaldi 6.5.3206.53 (Stable channel) (64-bit)

**Comment by ktg5** [comment]
This is because I'm 100% STUPID and meant to make the background of the HD badge change and not the whole thing change. I'll fix this and put it in the next update.

**Comment by OleExploder** [comment]
It's alright man, thanks.
