### ISSUE TITLE
the player bar doesnt properly stretch out across the entire bottom when the player size is smaller

### ISSUE THREAD

**Issue by JennyBean333** [ktg5/PlayerTube#19]
### A clear and concise description of what the bug is.

when customtube is enabled the player is always smaller in anything pre-2014 no matter if you have auto resize turned off and it seems that the player being smaller causes it to improperly stretch across. funnily if you just simply go to default current theme with customtube still on it breaks it *more* by making the seek bar turn invisible, no idea what could make that specifically react like that, just giving a notice in case its another issue to check out (shown in last image).
this issue effects all themes
first image is what it looks with customtube enabled and on the 2012 theme to match the 2012 player with the bar not stretching to the right all the way (weird button stuff in the top left is a layout bug with customtube and not due to playertube) and second is showing customtube fully disabled to prove that the issue is only due to the player being smaller from customtube rather than any other customization thing (which aren't on). third image shows how the 2006 theme looks which is obviously in a worse condition than the others due to still being a wip.

### If applicable, add screenshots to help explain your problem.

![image](https://github.com/ktg5/PlayerTube/assets/102128447/4136b371-416c-4766-b362-6a8452318e24)
![image](https://github.com/ktg5/PlayerTube/assets/102128447/6b03b83a-8901-498f-940b-37f611dcb915)
![image](https://github.com/ktg5/PlayerTube/assets/102128447/efcbe1c0-11c1-4f8c-bf44-d8dba0e9ffd9)
![image](https://github.com/ktg5/PlayerTube/assets/102128447/4d87a7e7-faa6-4392-9c50-0974871e7a1e)

### What should actually happen instead of the issue.

obviously the bar should stretch out all the way

### Steps to reproduce the behavior.

have a small sized player in customtube (any pre-2014 theme or just leaving it smaller in settings for 2014 and above)

### PlayerTube settings. (Can be found under "Import, Copy, or Reset Settings")

{
 "year": "2012",
 "showReleaseNotes": true,
 "alternateMode": false,
 "autoplayButton": false,
 "heatMapToggle": false,
 "fullyExtendBar": false,
 "fakeBarToggle": true,
 "toggleFadeOut": false,
 "endScreenToggle": true,
 "embedOtherVideos": true,
 "toggleWatermark": true,
 "toggleRoundedCorners": false,
 "togglePaidContent": false,
 "toggleInfoCards": true,
 "customTheme": false,
 "controlsBack": null,
 "settingsBgColor": null,
 "progressBarColor": null,
 "progressBarBgColor": null,
 "volumeSliderBack": null,
 "scrubberIcon": null,
 "scrubberIconHover": null,
 "scrubberPosition": null,
 "scrubberSize": null,
 "scrubberHeight": null,
 "scrubberWidth": null,
 "scrubberTop": null,
 "scrubberLeft": null
}
            

### Browser / Extension information.

using firefox

**Comment by ktg5** [comment]
This is because of all the different sizes that CustomTube forces on the player's width, Could be multiple other settings I haven't messed around with, but I'll see if I can fix all of them.

**Comment by ktg5** [comment]
Sending out a fix to the beta/dev builds, and yes, 2006 is a WIP.
