### ISSUE TITLE
narrow video is stretched (zoomed) to fit

### ISSUE THREAD

**Issue by veksha** [ktg5/PlayerTube#20]
### A clear and concise description of what the bug is.

narrow video is stretched (zoomed) to fit the width

### If applicable, add screenshots to help explain your problem.

without PlayerTube:
<img width="593" alt="ghost_BGuQNCDFXr" src="https://github.com/ktg5/PlayerTube/assets/275333/b7360957-720d-4215-8d7a-ce4dc03cb769">
with PlayerTube:
<img width="595" alt="ghost_O1VhdeZBIn" src="https://github.com/ktg5/PlayerTube/assets/275333/a16fd873-b26f-4bdf-94f8-a5d2462363d9">

### What should actually happen instead of the issue.

see screenshot 1

### Steps to reproduce the behavior.

1. enable PlayerTube with settings below.
2. find narrow video and play.

### PlayerTube settings. (Can be found under "Import, Copy, or Reset Settings")

{
 "autoplayButton": true,
 "controlsBack": null,
 "customTheme": false,
 "darkMode": false,
 "embedOtherVideos": false,
 "endScreenToggle": true,
 "fakeBarToggle": true,
 "fullyExtendBar": false,
 "heatMapToggle": true,
 "progressBarBgColor": null,
 "progressBarColor": null,
 "scrubberHeight": null,
 "scrubberIcon": null,
 "scrubberIconHover": null,
 "scrubberLeft": null,
 "scrubberPosition": null,
 "scrubberSize": null,
 "scrubberTop": null,
 "scrubberWidth": null,
 "settingsBgColor": null,
 "showReleaseNotes": true,
 "toggleFadeOut": true,
 "toggleInfoCards": true,
 "togglePaidContent": false,
 "toggleRoundedCorners": true,
 "toggleWatermark": true,
 "volumeSliderBack": null,
 "year": "2006"
}
            

### Browser / Extension information.

Ghost Browser (Built on Chromium)
Version 2.2.0.1 (Official Build) (64-bit)

PlayerTube Version
1.6.2

**Comment by veksha** [comment]
It can be a feature with On/Off toggle.

**Comment by ktg5** [comment]
Can you send in the video link?

**Comment by veksha** [comment]
yes https://youtu.be/Xs_9jxdE7JQ

**Comment by veksha** [comment]
brave browser = same

**Comment by ktg5** [comment]
Actually I think I just fixed it lmao -- update will be up soon.

**Comment by ktg5** [comment]
Unsure if you're able to reopen this issue, but if this doesn't fix it - let me know.

**Comment by Blasterfaster** [comment]
The new update brings an opposite problem. The video is cropped regardless of aspect ratio until I go to Fullscreen. 

What it looks like.
![Screenshot 2024-01-28 223227](https://github.com/ktg5/PlayerTube/assets/109541777/f483960a-232b-43a9-ba75-d10ee551349c)

What it's meant to look like.
![image_2024-01-28_224151428](https://github.com/ktg5/PlayerTube/assets/109541777/45b1ae21-febe-4098-a361-4b06282f5729)

**PlayerTube Settings**

{
 "alternateMode": false,
 "autoplayButton": false,
 "controlsBack": null,
 "customTheme": false,
 "embedOtherVideos": true,
 "endScreenToggle": true,
 "fakeBarToggle": true,
 "fullyExtendBar": false,
 "heatMapToggle": false,
 "progressBarBgColor": null,
 "progressBarColor": null,
 "scrubberHeight": null,
 "scrubberIcon": null,
 "scrubberIconHover": null,
 "scrubberLeft": null,
 "scrubberPosition": null,
 "scrubberSize": null,
 "scrubberTop": null,
 "scrubberWidth": null,
 "settingsBgColor": null,
 "showReleaseNotes": true,
 "toggleFadeOut": false,
 "toggleInfoCards": true,
 "togglePaidContent": false,
 "toggleRoundedCorners": false,
 "toggleWatermark": true,
 "volumeSliderBack": null,
 "year": "2006"
}
            
**Browser/Extension Information**

Oprea GX Version 106.0.4998.61

PlayerTube Version 1.6.2.1

**Comment by ktg5** [comment]
Send video link?

**Comment by Blasterfaster** [comment]
https://www.youtube.com/watch?v=FiYXhkdis58

**Comment by ktg5** [comment]
If you can't see the thing above, I added an additional fix (+ another i forgot about) to this issue which should solve everything up to this point.
