### ISSUE TITLE
Wrong years displayed in "General Settings - Change year of Player"

### ISSUE THREAD

**Issue by vicclln** [ktg5/PlayerTube#21]
### A clear and concise description of what the bug is.

I see 2012, 2011, 2010, 2006 years instead of 2015, 2012, 2010, 2006 in "**General Settings** - Change year of Player". So, if I have actual 2015 year version enabled, it'll display as 2012.

### If applicable, add screenshots to help explain your problem.

![image](https://github.com/ktg5/PlayerTube/assets/110984123/ca40956f-9084-432b-ba49-d44e3726bc50)

### What should actually happen instead of the issue.

It needs to be displayed as 2015, 2012, 2010, 2006.

### Steps to reproduce the behavior.

Click at extension icon, and then at "Change year of player" field to see.

### PlayerTube settings. (Can be found under "Import, Copy, or Reset Settings")

```
{
 "alternateMode": false,
 "autoplayButton": false,
 "controlsBack": null,
 "customTheme": false,
 "embedOtherVideos": true,
 "endScreenToggle": true,
 "fakeBarToggle": true,
 "fullyExtendBar": false,
 "heatMapToggle": false,
 "progressBarBgColor": null,
 "progressBarColor": null,
 "scrubberHeight": null,
 "scrubberIcon": null,
 "scrubberIconHover": null,
 "scrubberLeft": null,
 "scrubberPosition": null,
 "scrubberSize": null,
 "scrubberTop": null,
 "scrubberWidth": null,
 "settingsBgColor": null,
 "showReleaseNotes": true,
 "toggleFadeOut": false,
 "toggleInfoCards": true,
 "togglePaidContent": false,
 "toggleRoundedCorners": false,
 "toggleWatermark": true,
 "volumeSliderBack": null,
 "year": "2012"
}
       
```     

### Browser & Extension information (& video if shown).

Based on Chromium 109 browser; PlayerTube v1.6.2.

**Comment by ktg5** [comment]
Those were the years that the players were removed, not added. I changed this a couple updates back because 2010 & 2006 are named the same.
