### ISSUE TITLE
2006 Player Timer Stuck

### ISSUE THREAD

**Issue by Blasterfaster** [ktg5/PlayerTube#22]
### A clear and concise description of what the bug is.

I'm not quite sure what causes it, but sometimes the part of the bar showing how much time is left will freeze, while also keeping the video bar moving properly.

### If applicable, add screenshots to help explain your problem.

What it looks like. 
![Screenshot 2024-01-31 225458](https://github.com/ktg5/PlayerTube/assets/109541777/0214f1a7-c585-4303-91ed-b89d77dc2101)

### What should actually happen instead of the issue.

What it should look like. 
![image_2024-01-31_225918663](https://github.com/ktg5/PlayerTube/assets/109541777/8379af11-9ef6-4f07-bf6d-054568f4fabe)

### Steps to reproduce the behavior.

To my knowledge it mainly affects non 16:9 videos.

### PlayerTube settings. (Can be found under "Import, Copy, or Reset Settings")

{
 "alternateMode": false,
 "autoplayButton": false,
 "controlsBack": null,
 "customTheme": false,
 "embedOtherVideos": true,
 "endScreenToggle": true,
 "fakeBarToggle": true,
 "fullyExtendBar": false,
 "heatMapToggle": false,
 "progressBarBgColor": null,
 "progressBarColor": null,
 "scrubberHeight": null,
 "scrubberIcon": null,
 "scrubberIconHover": null,
 "scrubberLeft": null,
 "scrubberPosition": null,
 "scrubberSize": null,
 "scrubberTop": null,
 "scrubberWidth": null,
 "settingsBgColor": null,
 "showReleaseNotes": true,
 "toggleFadeOut": false,
 "toggleInfoCards": true,
 "togglePaidContent": false,
 "toggleRoundedCorners": false,
 "toggleWatermark": true,
 "volumeSliderBack": null,
 "year": "2006"
}
            

### Browser & Extension information (& video if shown).

Oprea GX Version 106.0.4998.61

PlayerTube Version 1.6.2.1

**Comment by Blasterfaster** [comment]
Important to note this only happens when it's not in Fullscreen. Fullscreen works perfectly.

**Comment by Blasterfaster** [comment]
Video: https://www.youtube.com/watch?v=jNQXAC9IVRw

**Comment by Blasterfaster** [comment]
YouTube Redux, and while disabling "Disable Miniplayer" on that did fix any inconsistent loading on 16:9 videos, Non 16:9 videos still freeze the timer. No video page option are enabled.

**Comment by ktg5** [comment]
Can't seem to replicate this issue.
