### ISSUE TITLE
[ Bug ] the video doesn't show when i use the latest version

### ISSUE THREAD

**Issue by Not-A-Coder2023** [ktg5/PlayerTube#23]
### A clear and concise description of what the bug is.

The video doesn't even show up

### If applicable, add screenshots to help explain your problem.

![Screenshot 2024-02-10 101425](https://github.com/ktg5/PlayerTube/assets/136338164/c91018b1-f354-4109-be68-be5d66a548d1)

### What should actually happen instead of the issue.

The video should show up with the video player

### Steps to reproduce the behavior.

uhh i don't know

### PlayerTube settings. (Can be found under "Import, Copy, or Reset Settings")

{
 "year": "2012",
 "showReleaseNotes": true,
 "alternateMode": false,
 "autoplayButton": false,
 "heatMapToggle": false,
 "fullyExtendBar": false,
 "fakeBarToggle": true,
 "toggleFadeOut": false,
 "endScreenToggle": true,
 "embedOtherVideos": true,
 "toggleWatermark": true,
 "toggleRoundedCorners": false,
 "togglePaidContent": false,
 "toggleInfoCards": true,
 "customTheme": false,
 "controlsBack": null,
 "settingsBgColor": null,
 "progressBarColor": null,
 "progressBarBgColor": null,
 "volumeSliderBack": null,
 "scrubberIcon": null,
 "scrubberIconHover": null,
 "scrubberPosition": null,
 "scrubberSize": null,
 "scrubberHeight": null,
 "scrubberWidth": null,
 "scrubberTop": null,
 "scrubberLeft": null
}
            

### Browser & Extension information (& video if shown).

Floorp Browser 11.9.0 (64-bit)
PlayerTube v1.6.2
https://www.youtube.com/watch?v=QgGhx0fLGiM

**Comment by ktg5** [comment]
Do you have any other YouTube extensions by chance?

**Comment by ktg5** [comment]
Closing this due to no response.
