### ISSUE TITLE
[ Bug ] Embed Fixes & Resize Issues | [ 3rd-party ] YouTube Redux messes with PlayerTube

### ISSUE THREAD

**Issue by ZyrusplaysAnimations** [ktg5/PlayerTube#24]
### A clear and concise description of what the bug is.

There is 2 bugs in player. 
In embedded videos, the bar goes out of bounds.
When playing a video, the bar is struggling to stretch. It fixes by itself when the comments section loaded or not. Also the watch later button is blinking. This bug was found at version 1.6 and this bug is still present.

### If applicable, add screenshots to help explain your problem.

![image](https://github.com/ktg5/PlayerTube/assets/70579850/c6f40f99-54ee-405c-9b0a-1e7162b4e5e5)
Embedded video out of bounds

(Video can't be uploaded so I will post pics instead.)
![image](https://github.com/ktg5/PlayerTube/assets/70579850/b894719a-84ca-47d7-8dcd-a8217e9d1f33)
![image](https://github.com/ktg5/PlayerTube/assets/70579850/458701c1-b9ba-4e19-801c-7145122fe4d6)
Video player bar freaking out and watch later button blinks.

### What should actually happen instead of the issue.

1st Bug: The bar is not out of bounds
2nd Bug: Bar doesn't freak out and the watch later button is not blinking.

### Steps to reproduce the behavior.

1st Bug: Play an embedded video
2nd bug: Play any video

### PlayerTube settings. (Can be found under "Import, Copy, or Reset Settings")

```
{
 "alternateMode": true,
 "autoplayButton": false,
 "controlsBack": null,
 "customTheme": false,
 "darkMode": false,
 "embedOtherVideos": true,
 "endScreenToggle": true,
 "fakeBarToggle": true,
 "fullyExtendBar": false,
 "heatMapToggle": false,
 "progressBarBgColor": null,
 "progressBarColor": null,
 "scrubberHeight": null,
 "scrubberIcon": null,
 "scrubberIconHover": null,
 "scrubberLeft": null,
 "scrubberPosition": null,
 "scrubberSize": null,
 "scrubberTop": null,
 "scrubberWidth": null,
 "settingsBgColor": null,
 "showReleaseNotes": false,
 "toggleFadeOut": false,
 "toggleInfoCards": true,
 "togglePaidContent": false,
 "toggleRoundedCorners": false,
 "toggleWatermark": true,
 "volumeSliderBack": null,
 "year": "2011"
}
            
```

### Browser & Extension information (& video if shown).

1st Bug: Any site that has an embedded video
2nd bug: Extensions: Youtube redux (Even redux is turned off, it still happens),
Video: Any Video

**Comment by ktg5** [comment]
This could've been fixed in one of the latest beta/dev builds. When you have the time, please try the latest build on there, which you can find out on how to install via the README file.
If that doesn't fix the issue, I will work on making a solution soon.

**Comment by ktg5** [comment]
Also, the browser and extension information you provided is invalid. Please post your browser version and the PlayerTube build you were testing this bug on.

**Comment by ZyrusplaysAnimations** [comment]
Chrome 121.0.6167.185
PlayerTube v1.6.2

**Comment by ZyrusplaysAnimations** [comment]
Tested out the dev builds, the bugs are still present.
PlayerTube v1.6.2.1

**Comment by ktg5** [comment]
It's to be safe than sorry to check this, do you have any other YouTube extensions installed?

**Comment by ZyrusplaysAnimations** [comment]
Youtube redux (Also deactivated it and removed it but the bug is still present).
Return Youtube Dislikes

**Comment by ktg5** [comment]
Unsure if this will solve this issue, but try out this build: https://github.com/ktg5/PlayerTube/actions/runs/7966665613

**Comment by ZyrusplaysAnimations** [comment]
Bar getting out of bounds on embedded videos is fixed.
![image](https://github.com/ktg5/PlayerTube/assets/70579850/18e0fd6c-cd9e-49fa-824d-857856f1181d)

The bar is ok when youtube redux is disabled. But when enabled, there is a gap. I think that is a bug to Redux I think.
![image](https://github.com/ktg5/PlayerTube/assets/70579850/4e71d5a5-10f5-4b4f-90e7-f4f207c56462)
*Redux Disabled

![image](https://github.com/ktg5/PlayerTube/assets/70579850/9698dcbd-2788-4c47-a2a2-d141df0ab704)
*Redux Enabled (Hovered my cursor.)

PlayerTube V1.6.3

**Comment by ktg5** [comment]
Ah, this is a 3rd-party issue. I'll get to seeing what's causing this.

**Comment by ktg5** [comment]
Okay just figured out the issue (I hope). Try disabling the "Use small video player" setting in Redux's settings, as that is what messes with the progress bar.
![image](https://github.com/ktg5/PlayerTube/assets/42522603/30768583-3b51-4e9c-bb71-c0ed0ae7a7a6)

**Comment by ktg5** [comment]
I might rewrite the way I get the Watch Later button onto the player before publishing the next update

**Comment by ZyrusplaysAnimations** [comment]
Update: The bug is back. Again. Sometimes the bar is ok and sometimes not. Even Redux is disabled.

**Comment by ktg5** [comment]
Welp I have no idea what would be causing this issue.

**Comment by ZyrusplaysAnimations** [comment]
I think the watch later button is causing the issue. Watch later button is trying to appear in the player, causing the bar to leave a gap and the watch later button blinks.

**Comment by ZyrusplaysAnimations** [comment]
![image](https://github.com/ktg5/PlayerTube/assets/70579850/6b2130f9-840a-4db2-8f15-413dda5060b7)
The bar wasn't trimmed and leaving a gap, the extended bar goes under the bar. It only happens on large resolution videos

**Comment by ktg5** [comment]
> ![image](https://private-user-images.githubusercontent.com/70579850/307050644-6b2130f9-840a-4db2-8f15-413dda5060b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NDMzNDksIm5iZiI6MTcwODY0MzA0OSwicGF0aCI6Ii83MDU3OTg1MC8zMDcwNTA2NDQtNmIyMTMwZjktODQwYS00ZGIyLThmMTUtNDEzZGRhNTA2MGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDIzMDQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ZjFjZmQwODAxZmZkNTk4Njk5OWE1YTIzYzExYWNjOWNlYzhiZjRhN2U3MzhjODViMmRhZjllOTg4YWJlMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IZTMFr21wIxXedZn92dXCyeoWiTNHsSqJh4EfYxWc2c) The bar wasn't trimmed and leaving a gap, the extended bar goes under the bar. It only happens on large resolution videos

Send link?

> I think the watch later button is causing the issue. Watch later button is trying to appear in the player, causing the bar to leave a gap and the watch later button blinks.

Could be. Might just rewrite the thing

**Comment by ktg5** [comment]
Was actually able to recreate the Watch Later button pretty easily, try this build when you have the time: https://github.com/ktg5/PlayerTube/actions/runs/8012519768

**Comment by ZyrusplaysAnimations** [comment]
Now the bar is no longer freaking out if the video's resolution is 16:9. But the embed bug is back.

> Send link?

https://www.youtube.com/watch?v=o087idMqWNA . The resolution is higher (kinda widescreen), that's why the bar goes underneath of another bar (Similar to the picture I sent).

**Comment by ktg5** [comment]
This build should fix everything up to this point: https://github.com/ktg5/PlayerTube/actions/runs/8013135188

**Comment by ZyrusplaysAnimations** [comment]
Embed is now ok. 
Bar is no longer freaking out.

But the large aspect ratio bug is still there. The bar is splitted into 2. I think it only happens when there are chapters in the video.
![image](https://github.com/ktg5/PlayerTube/assets/70579850/f1d8be64-a28e-4317-966c-7520f02a2afc)
*Bar hovered by cursor

Very large aspect ratio videos is not common, so I'll close this issue. Thank you for fixing bugs.
I'll open another issue if the aspect ratio bug is also affecting other videos.

**Comment by ktg5** [comment]
Thank you for sending them in! I'm unsure why the aspect ratio bug is still happening on your side, but it could just need more adjusting.
