### ISSUE TITLE
don't work with startube nor v3

### ISSUE THREAD

**Issue by Toodlebrat** [ktg5/PlayerTube#25]
### A clear and concise description of what the bug is.

don't work with startube nor v3

### If applicable, add screenshots to help explain your problem.

![image](https://github.com/ktg5/PlayerTube/assets/135457657/f19601a4-6e2d-45e2-b242-5b193c8ce820)

### What should actually happen instead of the issue.

work with startube and v3

### Steps to reproduce the behavior.

work with startube and v3

### PlayerTube settings. (Can be found under "Import, Copy, or Reset Settings")

            {
 "year": "2011",
 "showReleaseNotes": true,
 "alternateMode": false,
 "autoplayButton": false,
 "heatMapToggle": false,
 "fullyExtendBar": false,
 "fakeBarToggle": true,
 "toggleFadeOut": false,
 "endScreenToggle": true,
 "embedOtherVideos": true,
 "toggleWatermark": true,
 "toggleRoundedCorners": false,
 "togglePaidContent": false,
 "toggleInfoCards": true,
 "customTheme": false,
 "controlsBack": null,
 "settingsBgColor": null,
 "progressBarColor": null,
 "progressBarBgColor": null,
 "volumeSliderBack": null,
 "scrubberIcon": null,
 "scrubberIconHover": null,
 "scrubberPosition": null,
 "scrubberSize": null,
 "scrubberHeight": null,
 "scrubberWidth": null,
 "scrubberTop": null,
 "scrubberLeft": null
}
            

### Browser & Extension information (& video if shown).

don't work with startube nor v3

**Comment by ktg5** [comment]
This tells me nothing whatsoever. What about this extension or whatever it may be doesn't work with PlayerTube? Where can I this "StarTube"? What browser are you actually using? If you want to help with the extension, please try to write more than one sentence so that I can actually help you.
