### ISSUE TITLE
[ Bug ] 2006 Theme - Progress Bar extends more than it should

### ISSUE THREAD

**Issue by powerdollkirby** [ktg5/PlayerTube#26]
### A clear and concise description of what the bug is.

black line outside of the progress bar limit 

### If applicable, add screenshots to help explain your problem.

![Screenshot_20240712_185036](https://github.com/user-attachments/assets/3e473c02-0437-4f87-ac38-bee5bca6574c)

### What should actually happen instead of the issue.

look pretty

### Steps to reproduce the behavior.

play any video

### PlayerTube settings. (Can be found under "Import, Copy, or Reset Settings")

default and 2006 layout

### Browser & Extension information (& video if shown).

firefox 128.0

**Comment by ktg5** [comment]
Just want to make sure, as it's something I ask everyone; are you running any other extensions for YouTube? And also, have you tried [installing the latest dev build](https://github.com/ktg5/PlayerTube?tab=readme-ov-file#beta--dev-builds)? Sometimes that can do the trick.

**Comment by ktg5** [comment]
Any update on this?

**Comment by powerdollkirby** [comment]
i just checked in waterfox with no extensions other than ublock and still shows like that just with the 2006 layout, the rest are ok

**Comment by powerdollkirby** [comment]
i realised it happens sometimes, sometimes is fine sometimes is not

**Comment by ktg5** [comment]
I've been using the 2006 theme a little more too and I get the same thing. Unsure what it could be but I'll see if I can solve it sometime.

**Comment by powerdollkirby** [comment]
yeah no worries

**Comment by powerdollkirby** [comment]
the problem seems to be youtube redux when it resizes the player, so apparently it keeps the old values and so the bar keeps showing outside the now  resized/smaller player

**Comment by ktg5** [comment]
There's a page included with PlayerTube that's called "Extension Support" which has recommended settings for the extensions I've had experience with. If you go to one of the pages linked in the extension popup, you can find the other pages PlayerTube has.

**Comment by powerdollkirby** [comment]
that seems to fix the issue now its just a bit buggy haha with a small extra space at the end
![image](https://github.com/user-attachments/assets/93ed5056-e723-4595-b643-e25d752ac92e)
