### ISSUE TITLE
[ Bug ] Video player bar bug from Feb. 18 is back again. 

### ISSUE THREAD

**Issue by ZyrusplaysAnimations** [ktg5/PlayerTube#29]
### A clear and concise description of what the bug is.

When playing a video, the bar is incorrectly stretched. It doesn't fix by itself when the comments section is loaded. This bug is previously fixed but the bug returns at 1.7.2. The Bar is not freaking out but there is a gap.

### If applicable, add screenshots to help explain your problem.

![image](https://github.com/user-attachments/assets/0caa1642-247a-4b7e-9d5b-cd23ce9606b1)

### What should actually happen instead of the issue.

Player bar should be stretched to the whole video frame

### Steps to reproduce the behavior.

Play any video

### PlayerTube settings. (Can be found under "Import, Copy, or Reset Settings")

   {
 "alternateMode": false,
 "autoplayButton": false,
 "controlsBack": null,
 "customTheme": false,
 "darkMode": false,
 "embedOtherVideos": true,
 "endScreenToggle": true,
 "fakeBarToggle": true,
 "fullyExtendBar": false,
 "heatMapToggle": false,
 "progressBarBgColor": null,
 "progressBarColor": null,
 "scrubberHeight": null,
 "scrubberIcon": null,
 "scrubberIconHover": null,
 "scrubberLeft": null,
 "scrubberPosition": null,
 "scrubberSize": null,
 "scrubberTop": null,
 "scrubberWidth": null,
 "settingsBgColor": null,
 "showReleaseNotes": false,
 "toggleFadeOut": false,
 "toggleInfoCards": true,
 "togglePaidContent": false,
 "toggleRoundedCorners": false,
 "toggleWatermark": true,
 "volumeSliderBack": null,
 "year": "2011"
}
            

### Browser & Extension information (& video if shown).

Youtube Redux (Bar bugged even this extension is disabled)
Return Youtube Dislikes

**Comment by ktg5** [comment]
I think I might know what is causing this. Open your console and check for "TrustedHTML" and see if anything pops up. If so, trying updating to the latest beta/dev build. YouTube updated their website just recently to have this in place to make injected scripting a little bit harder. I fixed this yesterday and never got to send in the changes.

**Comment by ZyrusplaysAnimations** [comment]
Installed the latest beta, looks like that bug is fixed in that version.

**Comment by ZyrusplaysAnimations** [comment]
Closing this issue, Bug fixed on version 1.8.
