### ISSUE TITLE
[ Bug ] Embed issue and can't access info cards

### ISSUE THREAD

**Issue by ZyrusplaysAnimations** [ktg5/PlayerTube#30]
### A clear and concise description of what the bug is.

2 Bugs.
The first bug is the embedded player is shifted to the top but the video is unaffected.
The Second bug is the info cards, clicking the icon doesn't show the cards.

### If applicable, add screenshots to help explain your problem.

Bug 1:
![image](https://github.com/user-attachments/assets/9174425e-311b-48bd-9e70-4d004302aa21)

Bug 2: Cannot screenshot since it wouldn't show up.

### What should actually happen instead of the issue.

Bug 1: Embedded controls position is fixed
Bug 2: Can Access info cards

### Steps to reproduce the behavior.

Bug 1: Play a random embedded video
Bug 2: Play a random video with info cards

### PlayerTube settings. (Can be found under "Import, Copy, or Reset Settings")

```
 {
 "alternateMode": false,
 "autoplayButton": false,
 "controlsBack": null,
 "customTheme": false,
 "embedOtherVideos": true,
 "endScreenToggle": true,
 "fakeBarToggle": true,
 "fullyExtendBar": false,
 "heatMapToggle": false,
 "progressBarBgColor": null,
 "progressBarColor": null,
 "scrubberHeight": null,
 "scrubberIcon": null,
 "scrubberIconHover": null,
 "scrubberLeft": null,
 "scrubberPosition": null,
 "scrubberSize": null,
 "scrubberTop": null,
 "scrubberWidth": null,
 "settingsBgColor": null,
 "showReleaseNotes": false,
 "toggleFadeOut": false,
 "toggleInfoCards": true,
 "togglePaidContent": false,
 "toggleRoundedCorners": false,
 "toggleSpinner": true,
 "toggleWatermark": true,
 "volumeSliderBack": null,
 "year": "2012"
}
```
            

### Browser & Extension information (& video if shown).

Chrome 128.0.6613.120 (Official Build) (64-bit) (cohort: Stable) 
Playertube Dev 1.8

**Comment by ktg5** [comment]
The first issue is just some styling issues with 2012 that I was able to solve, but the info card issue might be because YouTube changed how info cards show. Instead of popping up on the side of the video, they bring me down to the description. So I'm unsure about the info card stuff, but I'll be sending out an update to 1.8 Dev soon.

**Comment by ZyrusplaysAnimations** [comment]
Embed bug is Fixed on the latest version of PlayerTube Dev 1.8.
Info Cards (not the icon) is no longer on the player's ui because of youtube's design changes. (except embedded videos)
Closing this issue, Thank you for fixing bugs.
I will going to open another issue if I found another bug.
