### ISSUE TITLE
[ Bug ] When in theater mode theres a slight black bar under the player

### ISSUE THREAD

**Issue by gamerloch10** [ktg5/PlayerTube#31]
### A clear and concise description of what the bug is.

Pretty much just the title, not too much more to say

### If applicable, add screenshots to help explain your problem.

![image](https://github.com/user-attachments/assets/324d6862-25c3-495d-b3fc-00fcb2f72269)

### What should actually happen instead of the issue.

The player should be slightly taller to fill up that space if possible

### Steps to reproduce the behavior.

Just load up 2012 and go into theater mode

### PlayerTube settings. (Can be found under "Import, Copy, or Reset Settings")

            {
 "alternateMode": false,
 "autoplayButton": false,
 "controlsBack": null,
 "customTheme": false,
 "embedOtherVideos": true,
 "endScreenToggle": true,
 "fakeBarToggle": false,
 "fullyExtendBar": false,
 "heatMapToggle": false,
 "progressBarBgColor": null,
 "progressBarColor": null,
 "scrubberHeight": null,
 "scrubberIcon": null,
 "scrubberIconHover": null,
 "scrubberLeft": null,
 "scrubberPosition": null,
 "scrubberSize": null,
 "scrubberTop": null,
 "scrubberWidth": null,
 "settingsBgColor": null,
 "showReleaseNotes": true,
 "toggleFadeOut": true,
 "toggleInfoCards": true,
 "togglePaidContent": false,
 "toggleRoundedCorners": false,
 "toggleWatermark": true,
 "volumeSliderBack": null,
 "year": "2012"
}
            

### Browser & Extension information (& video if shown).

Unsure what this means, sorry!

**Comment by ktg5** [comment]
Sorry for the long wait, are you possibly using any other extensions when on YouTube?
And for browser & extension information, just send over the name of the internet browser you use when going onto YouTube.

**Comment by ktg5** [comment]
Nevermind, figured out the issue with latest commit
