### ISSUE TITLE
CustomTube's Custom Player Size Bug

### ISSUE THREAD

**Issue by ChikarinT** [ktg5/PlayerTube#5]
I use CustomTube when Custom Player Size is using the player is not full
![firefox_zsp43rli0t](https://github.com/ktg5/PlayerTube/assets/101120166/73450b1f-1a89-435d-883a-27403ae453ce)

**Comment by ktg5** [comment]
This issue is caused by this.
![image](https://github.com/ktg5/PlayerTube/assets/42522603/ab611bb3-4f4f-45ff-856a-c803fc1f847d)
Why CustomTube, it's not that difficult to change the player size. (Will be fixed on v1.3.1)
