### ISSUE TITLE
[Bug] Progress Bar not moving when video is playing

### ISSUE THREAD

**Issue by ItzNeon4ik** [ktg5/PlayerTube#6]
Progress bar, constantly stands at one point until there is no action in the player.

![image](https://github.com/ktg5/PlayerTube/assets/127669709/6318242d-4092-4188-b2bd-3fb6a54e4db8)

_(It shows that we are somewhere at start)_

![image](https://github.com/ktg5/PlayerTube/assets/127669709/605de881-459c-4706-8e6e-ee71da481ef1)

_(But if you hover the cursor on player, we are where we need to be)_

**Comment by ktg5** [comment]
This was an issue with the original script, and can't currently be fixed due to the YouTube player's current position not getting changed after a while of inactivity. The only way I believe I'd be able to solve this is to link up the extension to the actual YouTube script, which I don't know how to do. As of right now, there's nothing I can really do -- but I'll be sure to figure a way to solve this in the future.

**Comment by veksha** [comment]
hi. this extension adds progress bar to fullscreen. maybe you can check its code and find out how it works:
https://chrome.google.com/webstore/detail/permanent-progress-bar-fo/dammfdepmngjjoidfdbhkjboecgceamb

**Comment by ktg5** [comment]
> hi. this extension adds progress bar to fullscreen. maybe you can check its code and find out how it works: https://chrome.google.com/webstore/detail/permanent-progress-bar-fo/dammfdepmngjjoidfdbhkjboecgceamb

Thanks for this! I'll be sure to look at it when I can.

**Comment by ktg5** [comment]
There will be an update out soon to make this all work. Right now it is somewhat working! Although I can't figure out how the get the buffered/loaded progress, and can't use the API YouTube has that the extension [veksha](https://github.com/veksha) mentioned.
![ezgif-5-c20c56cb30](https://github.com/ktg5/PlayerTube/assets/42522603/4853fcd1-1a9a-4f03-afe3-fcb909c27919)
Also yes, that's an ugly custom theme I made in a couple of seconds just to be sure it works with them too.
It updates every second, but unsure if I would lower it to make it smoother. Don't think it'll really affect performance, but lemme know -- maybe every `.25` seconds?

**Comment by ktg5** [comment]
for now, read the [beta install guide](https://github.com/ktg5/PlayerTube#beta--dev-builds) until I get this posted up on all web-stores.
