### ISSUE TITLE
Not sure if this is because of CustomTube but I've been seeing this lately

### ISSUE THREAD

**Issue by xxHAKRxx** [ktg5/PlayerTube#7]
![image](https://github.com/ktg5/PlayerTube/assets/140458341/4a1c0c04-3e34-4841-a779-d88d40aa10a9)

**Comment by ktg5** [comment]
Did you change any of the player size values?

**Comment by xxHAKRxx** [comment]
I was using the 2013 layout, which had a smaller screen.

**Comment by ktg5** [comment]
Forgot to ask, what browser are you using?

**Comment by ktg5** [comment]
Can't seem to replicate this issue... Make sure you've updated to the latest version of the extension (v1.3.1) or [install one of the dev builds](https://github.com/ktg5/PlayerTube#beta--dev-builds)

**Comment by ktg5** [comment]
closed due to inactivity.
