### ISSUE TITLE
[ Bug ] Settings icon not displaying "HD" properly

### ISSUE THREAD

**Issue by PseudoDistant** [ktg5/PlayerTube#8]
Title

![image](https://github.com/ktg5/PlayerTube/assets/67613281/3d5de1dd-0508-4892-9f3f-78b703c57325)

I'm using default 2015 player settings

- PlayerTube v1.4
- Firefox 117.0.1-1

**Comment by ktg5** [comment]
You sure you're not using any extra YouTube extensions? This doesn't happen on my end.

**Comment by ktg5** [comment]
Did you make sure to disable this setting in CustomTube?
![image](https://github.com/ktg5/PlayerTube/assets/42522603/3839b4cf-de54-48b3-aa2c-c426f7b8c417)
There should be a message when installing or when the extension updates that talks about changing this setting in CustomTube

**Comment by ktg5** [comment]
might be an issue with the background script for the extension on FIrefox, will look into it.

**Comment by ktg5** [comment]
Thought I fixed this issue many times but could be broken again since CustomTube likes to do that. Did you perhaps change anything else in the CustomTube "Watch page" settings tab? Like the Video Player Size or something?
