### ISSUE TITLE
Progress Bar keeps fading out with "Fully extend the Progress Bar" enabled

### ISSUE THREAD

**Issue by Darthskullshot** [ktg5/PlayerTube#9]
Fully extended progress bar setting on the 2010

![New Project](https://github.com/ktg5/PlayerTube/assets/109248782/90fc7998-8e08-49f0-a674-815e47181d58)
Imagine this but it stayed.

**Comment by ktg5** [comment]
The feature was originally intended to fade out instead of moving down. I'll change this within the next update.

**Comment by Darthskullshot** [comment]
Ah ok makes sense
